# Generated by Django 4.1.1 on 2023-07-27 02:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('f_fabricacion', models.DateField(default=datetime.date(2015, 1, 1), validators=[django.core.validators.MinValueValidator(datetime.date(2015, 1, 1), 'Fecha mínima: año 2015')], verbose_name='Fecha de fabricación')),
                ('p_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de costo')),
                ('p_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de venta')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('laboratorio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.laboratorio')),
            ],
            options={
                'verbose_name': 'Director general',
                'verbose_name_plural': 'Directores generales',
            },
        ),
    ]
