# Generated by Django 4.1.1 on 2023-08-05 02:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='No informada', max_length=50),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='No informada', max_length=50),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='No informado', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='f_fabricacion',
            field=models.DateField(default=datetime.date(2015, 1, 1), validators=[django.core.validators.MinValueValidator(datetime.date(2015, 1, 1), 'Fecha mínima: año 2015')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
